### ISSUE TITLE
https://explorer.mydashwallet.org is currently giving 404.

### ISSUE THREAD

**Issue by greatwolf** [DeltaEngine/MyDashWallet#10]
Looks like explorer.mydashwallet.org has been down for at least a month or more. Any idea what happened to this Dash blockexplorer?

**Comment by BenjaminNitschke** [comment]
The explorer is still working fine: https://explorer.mydashwallet.org/insight/

The link has changed early December when we had to move some servers, change the telegram bot id and stuff like that. the redirection from the main page to /insight is currently broken, no idea why, it is basically a clone from https://insight.dash.org/insight/ since we removed most of our changes (which are still here on github, we just don't use them anymore, too much work to maintain and merge in the the main insight-ui)

**Comment by greatwolf** [comment]
That's good to know. Wasn't aware of the url change. Fixing the redirect from main page to /insight makes sense at some point in case others run into this issue.
