### ISSUE TITLE
old MyDashWallet building guide

### ISSUE THREAD

**Issue by m4hdi1995** [DeltaEngine/MyDashWallet#3]
Hello, it seems the new wallet is depended on old wallet for making transactions right? so where is the old MyDashWallet building guide?

**Comment by m4hdi1995** [comment]
@BenjaminNitschke any help on building old wallet? https://github.com/DeltaEngine/MyDashWallet/tree/54b73658120eb601929011e644792bd6a1291d84

**Comment by BenjaminNitschke** [comment]
sorry, we are not developing the old api atm, if you have any question for the new website, let us know.

the new site has no backend, but since not all features are 100% available in javascript right now, it depends on some very simple calls to build raw transactions and send signed transactions into the dash network, you can reproduce them in few lines of code in any language (e.g. node.js, c++, python, c#, java, doesn't matter).

also it seems like our proposal to continue MyDashWallet development is not getting much support, so we are not inclined atm to put much more time into the new website to replace all the old api calls into new plain javascript and explorer calls. In the future we will certainly go further and clean up everything (or any developer is free to modify our MyDashWallet code or fork it, so far no one has done it or helped in almost 2 years).

**Comment by BenjaminNitschke** [comment]
Also just noticed that the published code contains old unused asp.net core code, which is not needed, the new site runs purely on React.js

**Comment by m4hdi1995** [comment]
@BenjaminNitschke yes, got it thanks.
